### ISSUE TITLE
SPA Can not Log out

### ISSUE THREAD

**Issue by cparkinsonMYCM** [laravel/airlock#87]
- Airlock Version: 1.0
- Laravel Version: 7.0

### Description:
After setting up following the setup [here](https://laravel.com/docs/master/airlock#spa-authentication)
and configuring xsrf and cors, my SPA (in Angular) can log in but then cannot log out.

The docs say that I should use the "standard, session based authentication services that Laravel provides" [here](https://laravel.com/docs/master/airlock#spa-authenticating) so my login runs
```
Auth::attempt([...]);
```
and returns 200 or 401 on success or failure respectively.

And as is written [here](https://laravel.com/docs/master/authentication#authenticating-users) within my logout function I call 
```
Auth::logout();
```
but I receive
```
Method Illuminate\Auth\RequestGuard::logout does not exist.
```

The docs make no mention of modifying `config/auth.php`  to set the api guard there, and so I haven't, it is still 
```
'api' => [
    'driver' => 'token',
    'provider' => 'users',
    'hash' => false,
],
```

The token that I can see through the authenticated user is a [TransientToken](https://github.com/laravel/airlock/blob/master/src/TransientToken.php) and I cannot delete/revoke it..?

So until the session expires a user is logged in and cannot be logged out....
Am I missing something?

**Comment by leeovery** [comment]
You have to explicitly use the `web` guard to logout. Its due to the way Airlock registers the airlock guard using `viaRequest`.

I think there's probably a better way of handling it but for now, doing this works:

```
Auth::guard('web')->logout();
```

**Comment by cparkinsonMYCM** [comment]
@leeovery I suppose I should have seen that, thanks for the info!
Does indeed work, that'll do for now 👍

**Comment by TCM-dev** [comment]
It may or may not be related.
Thanks to the guard the function now executes but it does look it's not working.
This is my test :
`    public function test_user_can_logout()
    {
        Airlock::actingAs(
            factory(User::class)->create()
        );

        $this->assertAuthenticated();
        $response = $this->post('/logout');
        $response->assertNoContent();
        $this->assertGuest();
    }`

The test fails on the last line because the user still is authenticated
This is the logout function used : 
`    public function logout()
    {
        try {
            //log user out
            Auth::guard('web')->logout();

            return response()->json('', 204);
        } catch (\Exception $e) {
            //return error message
            return response()->json('error_logout', 500);
        }
    }`

Is it related ? Is there something I'm missing ?

**Comment by gofish543** [comment]
@TCM-dev Also encountering the issue with the user not being logged out

**Comment by TCM-dev** [comment]
Thank you a lot! Now my test works.

**Comment by nnnayeem** [comment]
For me `Auth::guard('web')->logout();` did not worked. But I did a little workaround and is working now.

For logging out I created a logout api route which will delete all token for the particular user. Though it is not perfect but served my purpose.

But what I can not understand is why the above solution did not worked for me. If anyone can shade a light feel free to do it.

**Comment by kedarv** [comment]
Yeah this doesn't actually seem to work anymore. @driesvints: can you see if there was a regression here?

**Comment by Niush** [comment]
`Auth::guard('web')->logout();` is working.
Would be better to mention this in the docs.

**Comment by jamesh-purr** [comment]
> Yeah this doesn't actually seem to work anymore. @driesvints: can you see if there was a regression here?
> 
> Actually, this could be related to using sanctum in a stateless mobile api context instead of SPA..

I am having this issue that Auth::guard('web')->logout(); isn't working. I am still authenticated with a SPA. @driesvints please can you advise what could be the reason why the above isn't invalidating the session cookie?

I have also tried using the built in logout route and that also doesn't invalidate the session cookie. Again I am still authenticated.

**Comment by jamesh-purr** [comment]
Scrap that, I think it must of been some browser bs going on as I put back the default logout route and incognito it worked just fine.

**Comment by atorscho** [comment]
`auth()->logout` works for me (SPA auth) as long as I don't add the `api:sanctum` middleware to this route. With this middleware active I get the `Method Illuminate\Auth\RequestGuard::logout does not exist` error.

**Comment by epixian** [comment]
> You have to explicitly use the `web` guard to logout. Its due to the way Airlock registers the airlock guard using `viaRequest`.
> 
> I think there's probably a better way of handling it but for now, doing this works:
> 
> ```
> Auth::guard('web')->logout();
> ```

Setting this in a `guard()` method within LoginController works for me.
```php
/**
 * Get the guard to be used during authentication.
 *
 * @return \Illuminate\Contracts\Auth\StatefulGuard
 */
protected function guard()
{
    return Auth::guard('web');
}
```

**Comment by Tofandel** [comment]
In addition to @atorscho 's comment the `auth:sanctum` middleware also causes the issue

**Comment by eskiesirius** [comment]
> You have to explicitly use the `web` guard to logout. Its due to the way Airlock registers the airlock guard using `viaRequest`.
> 
> I think there's probably a better way of handling it but for now, doing this works:
> 
> ```
> Auth::guard('web')->logout();
> ```

when using browser.. the user is still authenticated

**Comment by reza305z** [comment]
> 
> 
> `auth()->logout` works for me (SPA auth) as long as I don't add the `api:sanctum` middleware to this route. With this middleware active I get the `Method Illuminate\Auth\RequestGuard::logout does not exist` error.

I was devastated, but removing 'api:sanctum' middleware from logout made it work.
I think this issue should be solved as soon as possible

**Comment by nikoh-dev** [comment]
Hi,

Do you know why the issue has been closed ?
It seems that this has not been resolved in the last version of sanctum...

**Comment by NK0D1NG** [comment]
This issue is still present in the current sanctum version. I am using Laravel 9 and logging out inside a test is not possible. It's like the user authenticated with the actingAs-method persists for all requests inside the test.

**Comment by reza305z** [comment]
I can't even use withoutMiddleware() method on the logout route!!!

**Comment by ashik-meher** [comment]
Still facing the issue

**Comment by ashik-meher** [comment]
I dont understand why the issue is closed, it is not solved yet

**Comment by alalfakawma** [comment]
I had a problem like this, I did use `Auth::guard('web')->logout()`, it does work when using a single user, but after logging out. When I try to login again, using a _different_ user, it puts me in but throws a `401` error. The way I fixed this was by using flushing the session before calling the `logout()` method using `Session::flush()`. Idk what is the deal with that.

**Comment by TheBlindHawk** [comment]
@alalfakawma 
I also had the same issue, and after further checking the logs I found the part that explains it:
https://laravel.com/docs/11.x/sanctum#logging-in
> You should ensure that it authenticates the user using the standard, [session based authentication services that Laravel provides](https://laravel.com/docs/11.x/authentication#authenticating-users). Typically, this means using the web authentication guard.

The link redirects to the following where they explain the logout
https://laravel.com/docs/11.x/authentication#logging-out
So for Sanctum SPA the following worked for me:
```
Auth::logout();
Session::invalidate();
Session::regenerateToken();
```
Not sure if ```Session::regenerateToken();``` is necessary though

**Comment by DanielDeSousaDEV** [comment]
This solution worked for my API using SPA authentication:
```php
function logout(Request $request)
{
    // Invalidate the current session and regenerate CSRF token
    $request->session()->invalidate();
    $request->session()->regenerateToken();

    // Log the user out
    auth('web')->logout();

    // Return a successful response
    return response([
        'success' => true,
        'message' => 'Logged out successfully',
    ]);
}

```
